add doh, rework menu

diff --git a/ccbins_files/ccbins b/ccbins_files/ccbins
--- a/ccbins_files/ccbins
+++ b/ccbins_files/ccbins
@@ -39,10 +39,12 @@ set -x 2>$VERLOG
 # > You can start your MOD here.
 # > You can add functions, variables & etc.
 # > Rather than editing the default vars above.
-scriptver=18
+scriptver=19
 branch=testing
 # Curl uses boringssl - first appeared in Marshmallow - don't try using ssl in older android versions
-[ $API -lt 23 ] && alias curl="$MODDIR/curl -kLs" || alias curl="$MODDIR/curl -Ls"
+[ -f $MODDIR/.doh ] && flag=" --doh-url $(tail -n1 $MODDIR/.doh)"
+[ $API -lt 23 ] && alias curl="$MODDIR/curl -kLs$flag" || alias curl="$MODDIR/curl -Ls$flag"
+unset flag
 dir=`pwd`; bakloc=/data/local/ccbinsbackup
 locs="/system/bin /system/xbin /system/vendor/bin /system/vendor/xbin /system/product/bin /system/product/xbin"
 [ -f $MODDIR/.loc ] && insloc="$(cat $MODDIR/.loc)" || insloc=/system/bin
@@ -195,45 +197,10 @@ info() {
   done
 }
 
-binary_update_menu() {
-  clear
-  while true; do
-    echo "$div"
-    title_div "Binary Update Menu"
-    echo "$div"
-    echo "0: Go back to main menu"
-    if $autoupdate; then
-      echo "1: Disable automatic binary updates at launch"
-    else
-      echo "1: Enable automatic binary updates at launch (recommended)"
-      $online && echo "2: Check for binary updates"
-    fi
-    while true; do
-      read -r choice?'--> '
-      echo " "
-      case $choice in
-        0|1|2) break;;
-        q) quit;;
-        *) echo "Invalid option! Try again";;
-      esac
-    done
-    case $choice in
-      0) break;;
-      1) $autoupdate && { touch $MODDIR/.disable_autoupdate; autoupdate=false; } || { rm -f $MODDIR/.disable_autoupdate; autoupdate=true; };;
-      2) if $autoupdate || ! $online; then
-           echo "Invalid option! Try again"
-         else
-           check_bin_updates & e_spinner
-           [ -f $MODDIR/tmp ] && echo -e " - Done\n" || echo -e " - Binaries are up to date\n"
-         fi;;
-    esac
-  done
-}
-
 list_locs() {
   rm -f $MODDIR/tmp
   local num=0
-  echo "0: Go back to main menu"
+  echo "0: Go back to options menu"
   for i in $locs; do
     [ -d "$i" ] || continue
     num=$((num+1))
@@ -267,6 +234,91 @@ change_loc() {
     echo $insloc > $MODDIR/.loc
     echo -e "Install location has been changed to $insloc\n"
     break
+  done
+}
+
+binary_update_menu() {
+  clear
+  while true; do
+    echo "$div"
+    title_div "Binary Update Menu"
+    echo "$div"
+    echo "0: Go back to options menu"
+    if $autoupdate; then
+      echo "1: Disable automatic binary updates at launch"
+    else
+      echo "1: Enable automatic binary updates at launch (recommended)"
+      $online && echo "2: Check for binary updates"
+    fi
+    while true; do
+      read -r choice?'--> '
+      echo " "
+      case $choice in
+        0|1|2) break;;
+        q) quit;;
+        *) echo "Invalid option! Try again";;
+      esac
+    done
+    case $choice in
+      0) break;;
+      1) $autoupdate && { touch $MODDIR/.disable_autoupdate; autoupdate=false; } || { rm -f $MODDIR/.disable_autoupdate; autoupdate=true; };;
+      2) if $autoupdate || ! $online; then
+           echo "Invalid option! Try again"
+         else
+           check_bin_updates & e_spinner
+           [ -f $MODDIR/tmp ] && echo -e " - Done\n" || echo -e " - Binaries are up to date\n"
+         fi;;
+    esac
+  done
+}
+
+options_menu() {
+  clear
+  while true; do
+    echo "$div"
+    title_div "Options Menu"
+    echo "$div"
+    echo "0: Go back to main menu"
+    echo "1: Change install location"
+    echo "2: Binary Update Settings"
+    echo "3: DNS Poisoning Workaround (DOH)"
+    while true; do
+      read -r choice?'--> '
+      echo " "
+      case $choice in
+        0|1|2|3) break;;
+        q) quit;;
+        *) echo "Invalid option! Try again";;
+      esac
+    done
+    case $choice in
+      0) break;;
+      1) change_loc;;
+      2) binary_update_menu;;
+      3) while true; do
+           echo -e "\nWhich doh server?"
+           echo -e "You will need to restart ccbins for changes to take effect\n"
+           echo "0: Go back to options menu"
+           echo "1: None"
+           echo "2: Cloudflare"
+           echo "3: Alibaba (recommended for Chinese users)"
+           while true; do
+             read -r choice?'--> '
+             echo " "
+             case $choice in
+               0|1|2|3) break;;
+               q) quit;;
+               *) echo "Invalid option! Try again";;
+             esac
+           done
+           case $choice in
+             0) break;;
+             1) rm -f $MODDIR/.doh;;
+             2) echo -e "Cloudflare\nhttps://cloudflare-dns.com/dns-query" > $MODDIR/.doh;;
+             3) echo -e "Alibaba\nhttps://dns.alidns.com/dns-query" > $MODDIR/.doh;;
+           esac
+         done;;
+    esac
   done
 }
 
@@ -600,35 +652,33 @@ while true; do
   echo "$div"
   title_div "Binary Installer"
   echo "$div"
-  echo "Current install location:"
-  echo "$insloc"
-  echo "$div"
-  echo "Auto-update binaries at launch:"
-  $autoupdate && echo "Enabled (recommended)" || echo "Disabled"
-  echo "$div"
+  echo "Options:"
+  echo "Current install location: $insloc"
+  $autoupdate && echo "Auto-update binaries at launch: Enabled (recommended)" || echo "Auto-update binaries at launch: Disabled"
+  [ -f $MODDIR/.doh ] && echo "DOH Server: $(head -n1 $MODDIR/.doh)" || echo "DOH Server: None"
   [ "$branch" == "master" ] || echo -e "Current branch:\n$branch\n$div"
+  echo "$div"
   title_div "Choose option"
   echo "$div"
   echo "0: Refresh CCbins (remove everything - start fresh)"
   echo "1: General Information"
-  echo "2: Change install location"
-  echo "3: Binary Update Settings"
-  echo "4: List all installed binaries"
-  echo "5: List all downloadable binaries"
-  echo "6: Remove binary"
-  $online && echo "7: Install binary"
-  $online && [ $API -ge 21 ] && echo "8: Install dynamic linked binary"
-  [ -s $MODDIR/.installed ] && echo "9: Backup current config"
-  [ -d $bakloc ] && echo -e "10: Restore last config\n11: Erase backup config"
+  echo "2: Options/Settings"
+  echo "3: List all installed binaries"
+  echo "4: List all downloadable binaries"
+  echo "5: Remove binary"
+  $online && echo "6: Install binary"
+  $online && [ $API -ge 21 ] && echo "7: Install dynamic linked binary"
+  [ -s $MODDIR/.installed ] && echo "8: Backup current config"
+  [ -d $bakloc ] && echo -e "9: Restore last config\n10: Erase backup config"
   echo "Type 'q' at any time to quit"
   while true; do
     read -r choice?'--> '
     echo " "
     case $choice in
-      0|1|2|3|4|5|6|99) break;;
-      7|8) $online && break || echo "Invalid option! Try again";;
-      9) [ -s $MODDIR/.installed ] && break || echo "Invalid option! Try again";;
-      10|11) [ -d $bakloc ] && break || echo "Invalid option! Try again";;
+      0|1|2|3|4|5|99) break;;
+      6|7) $online && break || echo "You're offline! Can't download any binaries";;
+      8) [ -s $MODDIR/.installed ] && break || echo "Nothing is installed! Nothing to backup";;
+      9|10) [ -d $bakloc ] && break || echo "No backup found!";;
       q) quit;;
       *) echo "Invalid option! Try again";;
     esac
@@ -637,10 +687,9 @@ while true; do
   case $choice in
     0) reset_mod; clear;;
     1) info; clear;;
-    2) change_loc; clear;;
-    3) binary_update_menu; clear;;
-    4) [ -s $MODDIR/.installed ] && { list_installed; clear; } || print_pause "No binaries installed!";;
-    5) clear
+    2) options_menu; clear;;
+    3) [ -s $MODDIR/.installed ] && { list_installed; clear; } || print_pause "No binaries installed!";;
+    4) clear
        echo "$div"
        title_div "Downloadable Binaries: "
        echo "$div"
@@ -656,12 +705,12 @@ while true; do
          esac
        done
        clear;;
-    6) [ -s $MODDIR/.installed ] && remove_binary_menu || print_pause "No binaries installed!\n";;
-    7) install_binary_menu;;
-    8) install_binary_menu -d;;
-    9) backup_config;;
-    10) restore_config;;
-    11) rm -rf $bakloc; print_pause "Backup config erased\n";;
+    5) [ -s $MODDIR/.installed ] && remove_binary_menu || print_pause "No binaries installed!\n";;
+    6) install_binary_menu;;
+    7) install_binary_menu -d;;
+    8) backup_config;;
+    9) restore_config;;
+    10) rm -rf $bakloc; print_pause "Backup config erased\n";;
     99) hidden_menu;;
   esac
 done
