fixes

diff --git a/ccbins_files/ccbins b/ccbins_files/ccbins
--- a/ccbins_files/ccbins
+++ b/ccbins_files/ccbins
@@ -2,6 +2,9 @@
 # Terminal Magisk Mod Template
 # by veez21 @ xda-developers
 
+# Setup kill switch
+trap "exit 0" 10
+proc="$$"
 
 # Magisk Module ID **
 ID="ccbins"
@@ -42,7 +45,7 @@ set -x 2>$VERLOG
 scriptver=19
 branch=testing
 # Curl uses boringssl - first appeared in Marshmallow - don't try using ssl in older android versions
-[ -f $MODDIR/.doh ] && flag=" --doh-url $(tail -n1 $MODDIR/.doh)"
+[ -f $MODDIR/doh ] && flag=" --doh-url $(tail -n1 $MODDIR/doh)"
 [ $API -lt 23 ] && alias curl="$MODDIR/curl -kLs$flag" || alias curl="$MODDIR/curl -Ls$flag"
 unset flag
 dir=`pwd`; bakloc=/data/local/ccbinsbackup
@@ -52,11 +55,9 @@ locs="/system/bin /system/xbin /system/vendor/bin /system/vendor/xbin /system/pr
 # redefined with curl
 test_connection() {
   (
-  for i in github google baidu; do
-    if curl --connect-timeout 3 -I https://www.$i.com | grep -q 'HTTP/.* 200' || ping -q -c 1 -W 1 $i.com >/dev/null; then
-      true
-    elif curl --connect-timeout 3 -I https://www.$i.com | grep -q 'HTTP/.* 200' || ping -q -c 1 -W 1 $i.com >/dev/null; then
-      true
+  for i in google baidu; do
+    if curl --connect-timeout 3 -I https://www.$i.com | grep -q 'HTTP/.* 200' || ping -q -c 1 -W 1 $i.com >/dev/null 2>&1; then
+      true; break
     else
       false
     fi
@@ -66,6 +67,7 @@ test_connection() {
 
 quit() {
   rm -f $MODDIR/tmp $MODDIR/dlerror
+  kill -10 $proc
   exit 0
 }
 
@@ -79,9 +81,16 @@ download_file() {
   local file="$1" url="$2"
   curl -o "$file" "$url"
   if [ "$file" == "$MODDIR/.checksums" ]; then
-    [ "$(head -n1 "$file")" == "checksums.txt" ] || { echo "Checksums download failed!"; quit; }
+    if [ ! -f "$file" ]; then
+      echo "Checksums download failed!"
+      [ -f $MODDIR/doh ] && echo -e "Try deleting $MODDIR/doh\nor disabling your vpn"
+      quit
+    elif [ "$(head -n1 "$file")" != "checksums.txt" ]; then
+      echo "Checksums download failed!"
+      quit
+    fi
   else
-    grep -Fq "`md5sum "$file" | awk '{print $1}'`" $MODDIR/.checksums || { rm -f "$file"; touch $MODDIR/dlerror; echo "Download error for $file!"; }
+    [ -f "$file" ] && grep -Fq "`md5sum "$file" | awk '{print $1}'`" $MODDIR/.checksums || { rm -f "$file"; touch $MODDIR/dlerror; echo "Download error for $file!"; }
   fi
 }
 
@@ -293,8 +302,8 @@ options_menu() {
     done
     case $choice in
       0) break;;
-      1) change_loc;;
-      2) binary_update_menu;;
+      1) change_loc; clear;;
+      2) binary_update_menu; clear;;
       3) while true; do
            echo -e "\nWhich doh server?"
            echo -e "You will need to restart ccbins for changes to take effect\n"
@@ -313,9 +322,9 @@ options_menu() {
            done
            case $choice in
              0) break;;
-             1) rm -f $MODDIR/.doh;;
-             2) echo -e "Cloudflare\nhttps://cloudflare-dns.com/dns-query" > $MODDIR/.doh;;
-             3) echo -e "Alibaba\nhttps://dns.alidns.com/dns-query" > $MODDIR/.doh;;
+             1) rm -f $MODDIR/doh; break;;
+             2) echo -e "Cloudflare\nhttps://cloudflare-dns.com/dns-query" > $MODDIR/doh; break;;
+             3) echo -e "Alibaba\nhttps://dns.alidns.com/dns-query" > $MODDIR/doh; break;;
            esac
          done;;
     esac
@@ -651,13 +660,10 @@ echo " "
 while true; do
   echo "$div"
   title_div "Binary Installer"
-  echo "$div"
-  echo "Options:"
   echo "Current install location: $insloc"
   $autoupdate && echo "Auto-update binaries at launch: Enabled (recommended)" || echo "Auto-update binaries at launch: Disabled"
-  [ -f $MODDIR/.doh ] && echo "DOH Server: $(head -n1 $MODDIR/.doh)" || echo "DOH Server: None"
-  [ "$branch" == "master" ] || echo -e "Current branch:\n$branch\n$div"
-  echo "$div"
+  [ -f $MODDIR/doh ] && echo "DOH Server: $(head -n1 $MODDIR/doh)" || echo "DOH Server: None"
+  [ "$branch" == "master" ] || echo -e "$div\nCurrent branch: $branch"
   title_div "Choose option"
   echo "$div"
   echo "0: Refresh CCbins (remove everything - start fresh)"
